"""Blender-side controls for the external local VGGT scene service."""

from __future__ import annotations

import json
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import bpy
from bpy.props import BoolProperty, StringProperty


def _service_url(scene: bpy.types.Scene, path: str) -> str:
    return scene.bts_vggt_service_url.rstrip("/") + path


def _request_json(url: str, payload: dict[str, object] | None = None) -> dict[str, object]:
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    request = Request(url, data=data, headers={"Content-Type": "application/json"})
    with urlopen(request, timeout=10) as response:
        return json.loads(response.read().decode("utf-8"))


def _point_cloud_path(scene: bpy.types.Scene) -> Path:
    return Path(scene.bts_vggt_job_directory) / "input" / "scene_data" / "points.ply"


class BTS_OT_toggle_concept_scene(bpy.types.Operator):
    bl_idname = "bts.toggle_concept_scene"
    bl_label = "Concept Scene"
    bl_description = "Show or hide the Concept Scene controls"

    def execute(self, context: bpy.types.Context) -> set[str]:
        scene = context.scene
        scene.bts_concept_scene_expanded = not scene.bts_concept_scene_expanded
        return {"FINISHED"}


class BTS_OT_submit_vggt_job(bpy.types.Operator):
    bl_idname = "bts.submit_vggt_job"
    bl_label = "Generate VGGT Scene Data"
    bl_description = "Submit the selected image to the local VGGT scene service"

    @classmethod
    def poll(cls, context: bpy.types.Context) -> bool:
        return bool(context.scene.bts_concept_image_path)

    def execute(self, context: bpy.types.Context) -> set[str]:
        scene = context.scene
        image_path = Path(scene.bts_concept_image_path).expanduser()
        if not image_path.is_file():
            self.report({"ERROR"}, "Choose an existing concept image first")
            return {"CANCELLED"}

        try:
            result = _request_json(
                _service_url(scene, "/jobs"),
                {
                    "image_path": str(image_path.resolve()),
                    "bundle_adjustment": scene.bts_vggt_bundle_adjustment,
                },
            )
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as exc:
            scene.bts_vggt_job_status = f"Service unavailable: {exc}"
            self.report({"ERROR"}, "Cannot reach local VGGT service on port 8765")
            return {"CANCELLED"}

        job_id = result.get("job_id")
        status_url = result.get("status_url")
        if not isinstance(job_id, str) or not isinstance(status_url, str):
            self.report({"ERROR"}, "VGGT service returned an invalid job response")
            return {"CANCELLED"}

        scene.bts_vggt_job_id = job_id
        scene.bts_vggt_status_path = status_url
        scene.bts_vggt_job_directory = ""
        scene.bts_vggt_job_status = "Queued"
        self.report({"INFO"}, f"VGGT job {job_id[:8]} queued")
        return {"FINISHED"}


class BTS_OT_check_vggt_job(bpy.types.Operator):
    bl_idname = "bts.check_vggt_job"
    bl_label = "Check VGGT Job"

    @classmethod
    def poll(cls, context: bpy.types.Context) -> bool:
        return bool(context.scene.bts_vggt_status_path)

    def execute(self, context: bpy.types.Context) -> set[str]:
        scene = context.scene
        try:
            result = _request_json(_service_url(scene, scene.bts_vggt_status_path))
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as exc:
            scene.bts_vggt_job_status = f"Status request failed: {exc}"
            self.report({"ERROR"}, "Cannot read VGGT job status")
            return {"CANCELLED"}

        status = result.get("status", "unknown")
        error = result.get("error")
        directory = result.get("directory")
        log_tail = result.get("log_tail")
        if isinstance(directory, str):
            scene.bts_vggt_job_directory = directory
        if isinstance(log_tail, str):
            scene.bts_vggt_log_tail = log_tail
        scene.bts_vggt_job_status = str(status if not error else f"{status}: {error}")
        self.report({"INFO"}, f"VGGT job status: {status}")
        return {"FINISHED"}


class BTS_OT_import_vggt_point_cloud(bpy.types.Operator):
    bl_idname = "bts.import_vggt_point_cloud"
    bl_label = "Import VGGT Point Cloud"
    bl_description = "Import the point cloud generated by the completed VGGT job"

    @classmethod
    def poll(cls, context: bpy.types.Context) -> bool:
        return _point_cloud_path(context.scene).is_file()

    def execute(self, context: bpy.types.Context) -> set[str]:
        point_cloud = _point_cloud_path(context.scene)
        if not hasattr(bpy.ops.wm, "ply_import"):
            self.report({"ERROR"}, "This Blender version does not provide the PLY import operator")
            return {"CANCELLED"}

        try:
            bpy.ops.wm.ply_import(filepath=str(point_cloud))
        except RuntimeError as exc:
            self.report({"ERROR"}, f"Could not import VGGT point cloud: {exc}")
            return {"CANCELLED"}

        for obj in context.selected_objects:
            obj.name = "VGGT_PointCloud"
        self.report({"INFO"}, "VGGT point cloud imported")
        return {"FINISHED"}


CLASSES = (
    BTS_OT_toggle_concept_scene,
    BTS_OT_submit_vggt_job,
    BTS_OT_check_vggt_job,
    BTS_OT_import_vggt_point_cloud,
)


def register() -> None:
    for cls in CLASSES:
        bpy.utils.register_class(cls)
    bpy.types.Scene.bts_concept_scene_expanded = BoolProperty(default=False)
    bpy.types.Scene.bts_concept_image_path = StringProperty(subtype="FILE_PATH")
    bpy.types.Scene.bts_vggt_service_url = StringProperty(default="http://127.0.0.1:8765")
    bpy.types.Scene.bts_vggt_bundle_adjustment = BoolProperty(default=False)
    bpy.types.Scene.bts_vggt_job_id = StringProperty(options={"HIDDEN"})
    bpy.types.Scene.bts_vggt_status_path = StringProperty(options={"HIDDEN"})
    bpy.types.Scene.bts_vggt_job_directory = StringProperty(options={"HIDDEN"})
    bpy.types.Scene.bts_vggt_log_tail = StringProperty(options={"HIDDEN"})
    bpy.types.Scene.bts_vggt_job_status = StringProperty(default="Service not contacted")


def unregister() -> None:
    for name in (
        "bts_vggt_job_status",
        "bts_vggt_job_directory",
        "bts_vggt_log_tail",
        "bts_vggt_status_path",
        "bts_vggt_job_id",
        "bts_vggt_bundle_adjustment",
        "bts_vggt_service_url",
        "bts_concept_image_path",
        "bts_concept_scene_expanded",
    ):
        delattr(bpy.types.Scene, name)
    for cls in reversed(CLASSES):
        bpy.utils.unregister_class(cls)